name: Maven Build and Deploy to EC2

on:
  push:
    branches:
      - main # Triggers when you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

     # Set up SSH Key properly
    - name: Set up SSH Key
      run: |
        mkdir -p /home/runner/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
        chmod 600 /home/runner/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> /home/runner/.ssh/known_hosts
      shell: bash

    - name: SCP JAR to EC2
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: target/*.jar # Change this according to your project's output JAR file
        target: ${{ secrets.TARGET_PATH }}

    - name: Restart EC2 Service
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl stop my-app.service || true
          sudo cp ${{ secrets.TARGET_PATH }}/*.jar /opt/demo-services/
          sudo systemctl start my-app.service